[package]
name = "tis100"
version = "0.1.0"
authors = ["Bill Fraser <wfraser@codewise.org>"]
edition = "2018"

[dependencies]
log = "0.4"
maplit = "1.0.1"
nom = "5.0"
num-traits = "0.2"
num-derive = "0.3"
rand = "0.7"
rand_chacha = "0.2"
stderrlog = "0.4"
structopt = "0.3"
