[package]
name = "tis100"
version = "0.1.0"
authors = ["Bill Fraser <wfraser@codewise.org>"]
edition = "2018"

[dependencies]
log = "0.4"
maplit = "1.0.1"
nom = "4.1.1"
num-traits = "0.2"
num-derive = "0.2"
rand = "0.5"
stderrlog = "0.4"
structopt = "0.2"
